services:
  web:
    build: ./client
    restart: always
    depends_on:
      service:
        condition: service_started
    environment:
      - NODE_ENV=production
      - SERVICE_ENDPOINT=service:3001
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8345:8345"
  service:
    build: ./service
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_USERNAME:-mongouser}:${MONGO_PASSWORD:-secure_mongo_pass_change_me}@database:27017
      - COOKIE_SECRET=${COOKIE_SECRET:-secure_cookie_secret_change_me_at_least_32_chars}
    depends_on:
      database:
        condition: service_started
    ports:
      - "3001:3001"
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongouser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secure_mongo_pass_change_me}

volumes:
  caddy_data:
  caddy_config:
