services:
  web:
    build: ./client
    restart: always
    depends_on:
      service:
        condition: service_started
    environment:
      - NODE_ENV=development
      - SERVICE_ENDPOINT=service:3001
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8345:8345"
  service:
    build: ./service
    restart: always
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:password@database:27017/p2piano?authSource=admin
      - REDIS_URI=redis://redis:6379
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "3001:3001"
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    image: redis:8-alpine
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  caddy_data:
  caddy_config:
  redis_data: