services:
  web-build:
    build: ./client
    depends_on:
      service:
        condition: service_started
    volumes:
      - static_content:/www
  proxy:
    build: ./proxy
    ports:
      - "8345:8345"
    volumes:
      - static_content:/www
      - caddy_data:/data
      - caddy_config:/config
  service:
    build: ./service
    environment:
      - NODE_ENV=production
    depends_on:
      database:
        condition: service_started
    ports:
      - "3001:3001"
  database:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

volumes:
  static_content:
  caddy_data:
  caddy_config: