name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - uses: actions/checkout@v4
    - name: Build the server image
      run: |
        cd service && docker build . --file Dockerfile --tag ghcr.io/${{github.actor}}/p2piano-server:latest
        
    - name: Push the server image
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        docker push ghcr.io/${{github.actor}}/p2piano-server:latest

  build-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - uses: actions/checkout@v4
    - name: Build the client image
      run: |
        cd client && docker build . --file Dockerfile --tag ghcr.io/${{github.actor}}/p2piano-client:latest
        
    - name: Push the client image
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        docker push ghcr.io/${{github.actor}}/p2piano-client:latest
