name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-server:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'server'

    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - uses: actions/checkout@v4
    - name: Build the server image
      run: |
        docker build . --file Dockerfile --tag p2piano-server:latest
        docker push ghcr.io/${{github.actor}}/p2piano-server:latest

  build-client:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'client'

    steps:
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/checkout@v4
    - name: Build the server image
      run: |
        docker build . --file Dockerfile --tag p2piano-client:latest
        docker push ghcr.io/${{github.actor}}/p2piano-client:latest
